### Page 65

## Data Preparation

### Learn, Test, and Evaluation Data

In [1]:
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
indices = np.random.permutation(len(iris.data))
indices

array([132, 130,  14,   1,  27,  68, 104,  23, 122,  65,  90,   3,  32,
       142,  44, 110,  85,  58,  92,  61,   0,  70, 101, 148, 100,  26,
        69,  63,  80,  71,  56, 120, 105,  79,  37, 131, 140,  64,  28,
       127,   9,  51,  25,  86,  29,  13, 141, 106, 119,  95,  82,  15,
        46,  49, 115,  38,  93,  41, 138,  48,  43, 134,   5, 133,  50,
        77, 117,   6,  18,  67,  21,  78, 146, 147, 103, 126,  99,  52,
       128,  88, 107,  81,  72,  94,  45,  40,  73,  59, 139, 149, 125,
         4,  24, 118,  30,  97,  60,  54,  33,  91, 123,  98,  87,   8,
        75,  96,  10,  36,  55, 137,  66,  16, 112,  84, 114, 129,   2,
       113, 144, 135,  19,  17,  39,  12, 143,  22,  42,  76,  31,  34,
        20, 145,   7,  35,  83, 121, 136, 116, 109,  57,  47, 124,  11,
        62, 111, 108,  74, 102,  89,  53])

In [4]:
n_test_samples = 12
learnset_data = iris.data[indices[:-n_test_samples]]
learnset_labels = iris.target[indices[:-n_test_samples]]
testset_data = iris.data[indices[-n_test_samples:]]
testset_labels = iris.target[indices[-n_test_samples:]]
print(learnset_data[:4], learnset_labels[:4])
print(testset_data[:4], testset_labels[:4])


[[6.4 2.8 5.6 2.2]
 [7.4 2.8 6.1 1.9]
 [5.8 4.  1.2 0.2]
 [4.9 3.  1.4 0.2]] [2 2 0 0]
[[7.2 3.6 6.1 2.5]
 [4.9 2.4 3.3 1. ]
 [4.6 3.2 1.4 0.2]
 [6.7 3.3 5.7 2.1]] [2 1 0 2]


### Splits with sklearn

In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
iris = load_iris()
data, labels = iris.data, iris.target

res = train_test_split(data, labels,
                      train_size=0.8,
                      test_size=0.2,
                      random_state=42)
train_data,test_data,train_labels,test_labels = res

n=7
print(f"The first {n} data sets: ")
print(test_data[:7])
print(f"The Corresponding {n} labels:")
print(test_labels[:7])

The first 7 data sets: 
[[6.1 2.8 4.7 1.2]
 [5.7 3.8 1.7 0.3]
 [7.7 2.6 6.9 2.3]
 [6.  2.9 4.5 1.5]
 [6.8 2.8 4.8 1.4]
 [5.4 3.4 1.5 0.4]
 [5.6 2.9 3.6 1.3]]
The Corresponding 7 labels:
[1 0 2 1 1 0 1]


### Stratified Random Sample

In [3]:
import numpy as np
print('ALL:',np.bincount(labels)/float(len(labels))* 100.0)
print("Training:",np.bincount(train_labels)/float(len(train_labels))*100.0)
print('Test:',np.bincount(test_labels)/float(len(test_labels))*100.0)

ALL: [33.33333333 33.33333333 33.33333333]
Training: [33.33333333 34.16666667 32.5       ]
Test: [33.33333333 30.         36.66666667]


In [4]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
iris = load_iris()
data, labels = iris.data, iris.target
res = train_test_split(data, labels,
                        train_size=0.8,
                        test_size=0.2,
                        random_state=42,
                        stratify=labels)
train_data, test_data, train_labels, test_labels = res
print('All:', np.bincount(labels) / float(len(labels)) * 100.0)
print('Training:', np.bincount(train_labels) / float(len(train_labels)) * 100.0)
print('Test:', np.bincount(test_labels) / float(len(test_labels))* 100.0)

All: [33.33333333 33.33333333 33.33333333]
Training: [33.33333333 33.33333333 33.33333333]
Test: [33.33333333 33.33333333 33.33333333]


In [5]:
content = np.loadtxt("data/strange_flowers.txt",delimiter=" ")
data = content[:, :-1]
labels = content[:,-1]
labels.dtype


dtype('float64')

In [6]:
labels.shape

(780,)

In [8]:
res = train_test_split(data, labels,
                      train_size=0.8,
                      test_size=0.2,
                      random_state=42,
                      stratify=labels)
train_data,test_data,train_labels,test_labels = res
#np.bincount expects non negative integers
print("ALL:",np.bincount(labels.astype(int))/float(len(labels))*100.0)
print("Training:",np.bincount(train_labels.astype(int))/float(len(train_labels))*100.0)
print("Test:",np.bincount(test_labels.astype(int))/float(len(test_labels))*100.0)


ALL: [ 0.         24.35897436 26.28205128 29.48717949 19.87179487]
Training: [ 0.         24.35897436 26.28205128 29.48717949 19.87179487]
Test: [ 0.         24.35897436 26.28205128 29.48717949 19.87179487]
